version: "3"

services:
  facade:
    container_name: facade
    build:
      context: .
      dockerfile: Dockerfile-facade
    ports:
      - "3000:3000"
    volumes:
      - .:/facade

  business:
    container_name: business
    build:
      context: .
      dockerfile: Dockerfile-business
    ports:
      - "3001:3001"
    volumes:
      - .:/business

  database:
    container_name: atv_sd_04_mongo
    image: mongo
    hostname: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./.docker/atv_sd_04_mongo:/data/db
