FROM python:3.8.1-slim

WORKDIR /data

RUN python -m pip install --upgrade pip

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY . .

EXPOSE 3002

CMD [ "python", "data/main.py" ]
