version: "3"

services:
  business:
    container_name: business
    build:
      context: .
      dockerfile: Dockerfile-business
    ports:
      - 3000:3000
    volumes:
      - .:/business

  database:
    container_name: atv_sd_04_mongo
    image: mongo
    hostname: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./.docker/atv_sd_04_mongo:/data/db
