FROM python:3.8.1-slim

WORKDIR /facade

RUN python3 -m pip install --upgrade pip

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY . .

CMD [ "python3", "facade/main.py" ]
