FROM python:3.8.1-slim

WORKDIR /business

RUN python -m pip install --upgrade pip

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY . .

CMD [ "python", "business/main.py" ]
